function two_way_linear_mixed_model
% Code runs a one-way linear mixed model

data_file_string = 'data\two_way_data.xlsx';

% Read data
d = readtable(data_file_string);

% Run the model
two_way_jitter( ...
    'data_table', d, ...
    'test_variable', 'pCa50', ...
    'factor_1', 'factor_1', ...
    'factor_2', 'factor_2', ...
    'grouping', 'tag', ...
    'calling_path_string', cd, ...
    'y_from_zero',0)

% Save the figure to an image file
print('two_way_jitter.png','-dpng')
